version: "3"

services:
  web:
    networks:
      - frontend
    volumes:
      - app-content:/opt/app/
    build: .
    logging:
      driver: none
    ports:
      - "6006:6006"
    tty: false
  accessibility:
    image: "node:14.16.0-alpine3.12"
    ipc: host
    working_dir: /opt/app/
    volumes:
      - app-content:/opt/app/
    depends_on:
      - web
    networks:
      - frontend
    command: npx wait-on http://web:6006 && yarn test:a11y

volumes:
  app-content:

networks:
  frontend:
    driver: bridge
