version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn install --frozen-lockfile
      - run: yarn test
  accessibility:
    docker: 
      - image: cimg/base:2021.03-20.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: docker info
      - run:
          name: Accessibility tests
          command: |
            set -x
            cat ./docker-compose.yml
            docker-compose -f ./docker-compose.yml up
workflows:
  tests:
    jobs:
      # - test
      - accessibility